# Generated by Django 4.0.7 on 2022-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('done', 'Done')], default='in_progress', max_length=128, verbose_name='status'),
        ),
    ]
