# Generated by Django 4.0.7 on 2022-08-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='done_at',
        ),
        migrations.RemoveField(
            model_name='list',
            name='status',
        ),
    ]
