# Generated by Django 4.0.7 on 2022-08-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('lists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='groups.group', verbose_name='group'),
        ),
    ]
