# Generated by Django 4.0.7 on 2022-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('done', 'done')], default='in_progress', max_length=128, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date and time when created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='date and time when last modified')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='date and time when done')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
    ]
